fix: allow cargo to use this repo for packaging
error: failed to prepare local package for uploading

Caused by:
  failed to select a version for the requirement `filter = "^0.2.1-dev"`
  candidate versions found which didn't match: 0.2.0, 0.1.0
  location searched: crates.io index